name: Build and upload to PyPI

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Build sdist
        run: pipx run build . --sdist
        
      - name: Set version number
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION = \"${GITHUB_REF_NAME:1}\"" > ./opuspocus/__about__.py

      - uses: actions/upload-artifact@v4
        with:
          name: build-sdist
          path: ./dist/opuspocus*.tar.gz

  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    # name: Build wheels on ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-2019, macos-13]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Build wheels
        run: python -m pip wheel --no-deps -w wheelhouse .

    #   - name: Install cibuildwheel
    #     run: python -m pip install cibuildwheel==2.12.0

    #   - name: Build wheels
    #     run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: build-wheels
          path: ./wheelhouse/opuspocus*.whl
          
  run_tests:
    needs: [build_sdist]
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: actions/download-artifact@v4
        with:
          name: build-sdist
          path: ./dist

      - name: Install
        run: python3 -m pip install ./dist/opuspocus*.whl

      - name: Run pytest
        run: python3 -m pytest -s -v ./tests/

  upload_pypi:
    needs: [build_wheels, build_sdist, run_tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-wheels
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: build-sdist
          path: ./dist
  
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
